"""Add webhook_url to documents

Revision ID: 35d89b7f0a7f
Revises: bacebaef973f
Create Date: 2026-04-17 15:10:21.845409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d89b7f0a7f'
down_revision: Union[str, Sequence[str], None] = 'bacebaef973f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('webhook_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'webhook_url')
    # ### end Alembic commands ###
