"""add_tenant_api_keys

Revision ID: fbb366fea798
Revises: 35d89b7f0a7f
Create Date: 2026-04-29 22:59:07.432485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb366fea798'
down_revision: Union[str, Sequence[str], None] = '35d89b7f0a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('llm_provider', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=False),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('key_hint', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_api_keys_tenant_id'), 'tenant_api_keys', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_api_keys_tenant_id'), table_name='tenant_api_keys')
    op.drop_table('tenant_api_keys')
    # ### end Alembic commands ###
